#!/bin/bash -e

# Define booleans, to be used when determineing which flags are enabled.
TRUE=0
FALSE=1

# Set all arguments as false, unless enabled with a flag.
print_ipv6=$FALSE
print_ipv4=$FALSE
print_loopback=$FALSE
print_device=$FALSE

# Ensure that flags are not specified from outside the script for the `ip` command
ip_flags=

# Parse arguments
for i in "$@";
do
    case $1 in
        -6|--v6)
            print_ipv6=$TRUE
            shift # past argument
            ;;
        -4|--v4)
            print_ipv4=$TRUE
            shift # past argument
            ;;
        -lo|--loopback)
            print_loopback=$TRUE
            shift # past argument
            ;;
        -dev|--device)
            print_device=$TRUE
            shift # past argument
            ;;
        -h|--help)
            echo "Prints the ip address of the local system. By default, no options are selected."
            echo "Options:"
            echo "  -6, --v6         Prints ipv6 addresses"
            echo "  -4, --v4         Prints ipv4 addresses"
            echo "  -lo, --loopback  Prints loopback addresses for the selected ip versions"
            echo "  -dev, --device   Prints device associated with each ip address in front of it"
            ;;
        *)
            echo "Unknown option $1"
            exit 1
            ;;
    esac
done

# Prints out ip addresses.
# If the loopback flag is enabled, it will also print the loopback ip addresses.
# If the device flag is enabled, the device name will be printed in front of each ip address.
# 
# Extra flags for the `ip` command can be specified by assinging them to the variable `ip_flags`
print_ip() {
    # Separator is now a newline instead of whitespace. Allows for-loop to split at newlines only.
    IFS=$'\n'

    for net_device in $(ip -oneline $ip_flags address show);
    do
        device="$(echo "$net_device" | awk '{print $2}')"
        ipv4addr="$(echo "$net_device" | awk '{print $4}' | cut -d/ -f1)"

        # Skip loopback addresses unless specifically asked for.
        if [[ $print_loopback -eq $TRUE ]] || ! [[ "$device" == "lo" ]];
        then
            if [[ $print_device -eq $TRUE ]]
            then echo "$device $ipv4addr"
            else echo "$ipv4addr"
            fi
        fi
    done
}

# Prints the devices ipv4 addresses, printing the loopback addresses if that flag is enabled.
printipv4() {
    # `-4` tell the `ip` command to print ipv4 addresses
    ip_flags="-4"

    print_ip
}

# Prints the devices ipv6 addresses, printing the loopback addresses if that flag is enabled.
printipv6() {
    # `-6` tell the `ip` command to print ipv6 addresses
    ip_flags="-6"

    print_ip
}

## SCRIPT BODY BEGINS HERE ##

if [[ $print_ipv4 -eq $TRUE ]];
then printipv4
fi

if [[ $print_ipv6 -eq $TRUE ]];
then printipv6
fi

exit 0
